version: '3'
services:

  video-streaming:
    image: partner-service
    build: 
      # context: ./
      dockerfile: Dockerfile
    container_name: partner-service
    ports:
     - "3003:3003"
    environment:
      - PORT=80
    restart: "no"