name: 'Partner CI to Docker Hub'

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: 'uniunity/partner-service'

jobs:
  docker:
    name: 'Build and Push to Docker Hub'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      id: set-tag
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Generate apiKey.js from 개별 시크릿
      run: |
        mkdir -p ./src/public/js
        cat <<EOF > ./src/public/js/apiKey.js
        const apiKeys = {
          KAKAO_API_KEY: "79c5295d7c90bb2123bbdb4eabb24301",
          SERVICE_KEY: "p0%2BHQGnCYhn4J%2BB0BJpY5cOD0thCQ29az7PS9MQ4gLwPqbZrSns3eFy4VZ%2BUSc95PAkZUjK%2FGiir%2FcMk1FAq4A%3D%3D",
          ENDPOINT: "https://apis.data.go.kr/B553077/api/open/sdsc2/"
        };

        export default apiKeys;
        EOF

        echo "apiKey.js 파일 생성 완료"

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
